server:
  port: 8080


spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: 123456
        url: jdbc:postgresql://localhost:5432/graphql_demo
        username: postgres
        
eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: userService
    instanceId: userService:userService:${random.value}
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 10
    status-page-url-path: /management/info
    health-check-url-path: /management/health
    hostname: localhost

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          [
              'health',
              'info',
          ]